-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "gameType" TEXT NOT NULL DEFAULT 'RAPID',
ADD COLUMN     "timeControl" TEXT NOT NULL DEFAULT '10|0';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "lastActiveBlitz" TIMESTAMP(3),
ADD COLUMN     "lastActiveBullet" TIMESTAMP(3),
ADD COLUMN     "lastActiveDaily" TIMESTAMP(3),
ADD COLUMN     "lastActiveRapid" TIMESTAMP(3),
ADD COLUMN     "ratingBlitz" INTEGER NOT NULL DEFAULT 1200,
ADD COLUMN     "ratingBullet" INTEGER NOT NULL DEFAULT 1200,
ADD COLUMN     "ratingDaily" INTEGER NOT NULL DEFAULT 1200,
ADD COLUMN     "ratingRapid" INTEGER NOT NULL DEFAULT 1200,
ADD COLUMN     "rdBlitz" DOUBLE PRECISION NOT NULL DEFAULT 350.0,
ADD COLUMN     "rdBullet" DOUBLE PRECISION NOT NULL DEFAULT 350.0,
ADD COLUMN     "rdDaily" DOUBLE PRECISION NOT NULL DEFAULT 350.0,
ADD COLUMN     "rdRapid" DOUBLE PRECISION NOT NULL DEFAULT 350.0;
